/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedElementDemo: typeof import('./src/components/AdvancedElementDemo.vue')['default']
    Algorithm: typeof import('./src/components/ZXHL/pages/models/algorithm/index.vue')['default']
    Config: typeof import('./src/components/ZXHL/pages/indicators/config/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElementPlusDemo: typeof import('./src/components/ElementPlusDemo.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Example: typeof import('./src/components/ZXHL/comp/pure/ms-select/example.vue')['default']
    Export: typeof import('./src/components/ZXHL/pages/data/export/index.vue')['default']
    ExtendedButton: typeof import('./src/components/ExtendedButton.vue')['default']
    ExtendedCard: typeof import('./src/components/ExtendedCard.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Import: typeof import('./src/components/ZXHL/pages/data/import/index.vue')['default']
    MainContent: typeof import('./src/components/layout/MainContent.vue')['default']
    Management: typeof import('./src/components/ZXHL/pages/data/management/index.vue')['default']
    MsSelect: typeof import('./src/components/ZXHL/comp/pure/ms-select/index.vue')['default']
    Overview: typeof import('./src/components/ZXHL/pages/evaluation/overview/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    Template: typeof import('./src/components/ZXHL/pages/indicators/template/index.vue')['default']
    Validation: typeof import('./src/components/ZXHL/pages/models/validation/index.vue')['default']
    Weight: typeof import('./src/components/ZXHL/pages/indicators/weight/index.vue')['default']
    ZxPureRouterView: typeof import('./src/components/ZXHL/comp/pure/ZxPureRouterView/index.vuex.vue')['default']
  }
}
