/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedElementDemo: typeof import('./src/components/AdvancedElementDemo.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElementPlusDemo: typeof import('./src/components/ElementPlusDemo.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Example: typeof import('./src/components/ZXHL/pure/ms-select/example.vue')['default']
    ExtendedButton: typeof import('./src/components/ExtendedButton.vue')['default']
    ExtendedCard: typeof import('./src/components/ExtendedCard.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MsSelect: typeof import('./src/components/ZXHL/pure/ms-select/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
